# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.2.0.schema.json

PackageIdentifier: UnityTechnologiesApS.Unity2021.3.10f1
PackageVersion: 2021.3.10f1
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.2.0

