# Created using wingetcreate 0.3.0.3
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: UnityTechnologiesApS.Unity2021.3.2f1
PackageVersion: 2021.3.2f1
Installers:
- InstallerUrl: https://download.unity3d.com/download_unity/d6360bedb9a0/Windows64EditorInstaller/UnitySetup64-2021.3.2f1.exe
  Architecture: x86
  InstallerType: nullsoft
  InstallerSha256: 760E2690A938B7F4F1CFC0AAAA25A9546CBD293B39852CD6A3103252BC743C43
ManifestType: installer
ManifestVersion: 1.0.0

