# Created using wingetcreate 0.3.0.3
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: UnityTechnologiesApS.Unity2021.3.2f1
PackageVersion: 2021.3.2f1
PackageLocale: en-US
Publisher: Unity Technologies ApS
PublisherUrl: https://unity.com/
PrivacyUrl: https://unity3d.com/legal/privacy-policy
Author: Unity Technologies ApS
PackageName: Unity 2021
PackageUrl: https://unity.com
License: Proprietary
LicenseUrl: https://unity3d.com/legal/terms-of-service/software
Copyright: Copyright © 2021 Unity Technologies Inc
CopyrightUrl: https://unity3d.com/legal/terms-of-service/software
ShortDescription: Break the barriers of reality and bring new ideas to life with Unity.
Moniker: unity-2021
Tags:
- unity
- unity editor
- game engine
- .net
- c#
- unity3d
- cross-platform
- ide
- editor
- multiplatform
ManifestType: defaultLocale
ManifestVersion: 1.0.0

